stages:
  - lint
  - test

ansible-lint:
  stage: lint
  image: python:3.10
  before_script:
    - pip install --upgrade pip
    - pip install "ansible-core==2.14.*" ansible-lint
  script:
    - ansible-lint --version
    - ansible-lint

molecule-syntax:
  stage: test
  image: python:3.10
  services:
    - name: docker:26-dind
      command: ["--host=tcp://0.0.0.0:2375", "--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apt-get update && apt-get install -y docker.io
    - pip install --upgrade pip
    - pip install "ansible-core==2.14.*" molecule molecule-plugins[docker]
  script:
    - molecule syntax
