---
- name: Converge
  hosts: all
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        openclaw_install_method: npm
        openclaw_llm_provider: "ollama"
        openclaw_llm_ollama_base_url: "http://127.0.0.1:11434"
        openclaw_workspace_init: false
