---
- name: Converge
  hosts: all
  roles:
    - role: babidi34.moltbot
      vars:
        moltbot_install_method: file
        moltbot_install_script_file: moltbot-install.sh
        moltbot_install_script_url: ""
        moltbot_model_primary: dummy/model
        moltbot_workspace_init: false
        moltbot_enable_user_service: false
