---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure python is available
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt-get update && apt-get install -y python3)
      changed_when: false
